<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CoursSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cours')->insert([
            [
                'codeUE' => 'ICT101',
                'intituleUE' => 'Introduction to Business Information Systems',
                'niveau_id' => 1,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT102',
                'intituleUE' => 'Object-Oriented Programming',
                'niveau_id' => 1,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT103',
                'intituleUE' => 'Introduction to Programming',
                'niveau_id' => 1,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT104',
                'intituleUE' => 'Computer systems',
                'niveau_id' => 1,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT105',
                'intituleUE' => 'Introduction to algorithms',
                'niveau_id' => 1,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT106',
                'intituleUE' => 'Data Structures and Patterns I',
                'niveau_id' => 1,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT107',
                'intituleUE' => 'Mathematics for computer science I',
                'niveau_id' => 1,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT108',
                'intituleUE' => 'Creating Web Application',
                'niveau_id' => 1,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT109',
                'intituleUE' => 'Discrete Mathematics I',
                'niveau_id' => 1,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT110',
                'intituleUE' => 'Database Analysis and Design',
                'niveau_id' => 1,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT111',
                'intituleUE' => 'Data Coding',
                'niveau_id' => 1,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ENG104',
                'intituleUE' => 'English I',
                'niveau_id' => 1,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'FRA104',
                'intituleUE' => 'Français I',
                'niveau_id' => 1,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT201',
                'intituleUE' => 'Introduction to Software Engineering',
                'niveau_id' => 2,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT202',
                'intituleUE' => 'Software Development for Mobile devices',
                'niveau_id' => 2,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT203',
                'intituleUE' => 'Database Systems',
                'niveau_id' => 2,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT204',
                'intituleUE' => 'Introduction to Operating System',
                'niveau_id' => 2,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT205',
                'intituleUE' => 'Introduction to Programming in .NET',
                'niveau_id' => 2,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT206',
                'intituleUE' => 'Introduction to Computer Network',
                'niveau_id' => 2,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT207',
                'intituleUE' => 'Software Development in Java I',
                'niveau_id' => 2,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT208',
                'intituleUE' => 'Computer Architecture',
                'niveau_id' => 2,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT213',
                'intituleUE' => 'Introduction to Computer Security and Risk Management',
                'niveau_id' => 2,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT214',
                'intituleUE' => 'Introduction to Cryptography',
                'niveau_id' => 2,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT215',
                'intituleUE' => 'Introduction to Computer Networking',
                'niveau_id' => 2,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT216',
                'intituleUE' => 'Network Administration',
                'niveau_id' => 2,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT217',
                'intituleUE' => 'Software Engineering',
                'niveau_id' => 2,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT218',
                'intituleUE' => 'Advanced Mobile Application Development',
                'niveau_id' => 2,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ENG203',
                'intituleUE' => 'English II',
                'niveau_id' => 2,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'FRA203',
                'intituleUE' => 'Français II',
                'niveau_id' => 2,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT300',
                'intituleUE' => 'Internship',
                'niveau_id' => 3,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT301',
                'intituleUE' => 'Software Architectures and Design',
                'niveau_id' => 3,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT302',
                'intituleUE' => 'Introduction to Artificial Intelligence',
                'niveau_id' => 3,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT303',
                'intituleUE' => 'Data Communication and Security',
                'niveau_id' => 3,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT304',
                'intituleUE' => 'Software Testing and Deployment',
                'niveau_id' => 3,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT305',
                'intituleUE' => 'Web Application Development',
                'niveau_id' => 3,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT306',
                'intituleUE' => 'Business Intelligence',
                'niveau_id' => 3,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT307',
                'intituleUE' => 'Computer Systems Engineering',
                'niveau_id' => 3,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT308',
                'intituleUE' => 'Software Development in Java II',
                'niveau_id' => 3,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT310',
                'intituleUE' => 'Professional Issues in IT',
                'niveau_id' => 3,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT313',
                'intituleUE' => 'Cyber and Internet Security',
                'niveau_id' => 3,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT314',
                'intituleUE' => 'Computer Forensics and Incident Response',
                'niveau_id' => 3,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT315',
                'intituleUE' => 'Network Application Development',
                'niveau_id' => 3,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT316',
                'intituleUE' => 'Digital communication',
                'niveau_id' => 3,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT317',
                'intituleUE' => 'Information system',
                'niveau_id' => 3,
                'semestre_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'codeUE' => 'ICT318',
                'intituleUE' => 'Java Enterprise Edition',
                'niveau_id' => 3,
                'semestre_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
